sudo: required
language: python
python:
  - 3.8
  - 3.7
  - 3.6

before_install:
    - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive

install: pip install -U tox-travis

# run tests
script: tox
